print "Hello world"

print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Behrooz Made Changes" 