print "Hello world"

print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"
print "Hello world"

print "Nick sucks"